name: uzphariminfo
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.4
  lottie: ^1.4.3
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  toast: ^0.3.0
  route_transitions: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  grouped_list: ^5.1.2
  flutter_slidable: ^2.0.0
  connectivity_plus: ^3.0.2
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

